"""SQLite implementation of ProjectRepository."""

from __future__ import annotations

import sqlite3
from datetime import datetime
from typing import Optional
from uuid import UUID

from contracts.base import PaginatedResult, PaginationParams, Result
from contracts.project import Project, ProjectCreateRequest, ProjectUpdateRequest
from database.repositories import ProjectRepository
from database.repositories.base import (
    project_row_to_dto,
    datetime_to_str,
    dict_to_json,
    uuid_to_str,
)


class SQLiteProjectRepository(ProjectRepository):
    """SQLite implementation of ProjectRepository."""

    def __init__(self, conn: sqlite3.Connection) -> None:
        self._conn = conn

    def create(self, request: ProjectCreateRequest) -> Result[Project]:
        """Create a new project."""
        project_id = UUID(int=0)  # Will be generated by application
        # The application should generate the UUID
        # We'll use the id from the request if provided, otherwise generate one
        project = Project(
            id=request.id if hasattr(request, "id") and request.id else UUID(int=0),
            name=request.name,
            description=request.description,
            metadata=request.metadata,
        )
        # If the project doesn't have an ID yet, generate one
        if project.id == UUID(int=0):
            from uuid import uuid4
            project = Project(
                id=uuid4(),
                name=request.name,
                description=request.description,
                metadata=request.metadata,
            )

        try:
            self._conn.execute(
                """
                INSERT INTO projects (project_id, name, description, status, metadata, created_at, updated_at)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    uuid_to_str(project.id),
                    project.name,
                    project.description,
                    "active",
                    dict_to_json(project.metadata),
                    datetime_to_str(project.created_at),
                    datetime_to_str(project.updated_at),
                ),
            )
            # Note: Transaction commit is managed by the caller (UnitOfWork/transaction context)
            return Result.ok(project)
        except sqlite3.IntegrityError as e:
            return Result.err(f"Project creation failed: {e}")
        except sqlite3.Error as e:
            return Result.err(f"Database error: {e}")

    def get(self, project_id: UUID) -> Result[Optional[Project]]:
        """Get a project by ID."""
        cursor = self._conn.execute(
            "SELECT * FROM projects WHERE project_id = ?",
            (uuid_to_str(project_id),),
        )
        row = cursor.fetchone()
        if row is None:
            return Result.ok(None)
        return Result.ok(project_row_to_dto(dict(row)))

    def update(self, project_id: UUID, request: ProjectUpdateRequest) -> Result[Optional[Project]]:
        """Update a project."""
        # First check if project exists
        existing = self.get(project_id)
        if not existing.success or existing.value is None:
            return Result.ok(None)

        project = existing.value
        updated_name = request.name if request.name is not None else project.name
        updated_description = request.description if request.description is not None else project.description
        updated_metadata = request.metadata if request.metadata is not None else project.metadata
        updated_at = datetime.now().isoformat()

        try:
            self._conn.execute(
                """
                UPDATE projects
                SET name = ?, description = ?, metadata = ?, updated_at = ?
                WHERE project_id = ?
                """,
                (
                    updated_name,
                    updated_description,
                    dict_to_json(updated_metadata),
                    updated_at,
                    uuid_to_str(project_id),
                ),
            )
            # Note: Transaction commit is managed by the caller (UnitOfWork/transaction context)

            updated_project = Project(
                id=project.id,
                name=updated_name,
                description=updated_description,
                metadata=updated_metadata,
                created_at=project.created_at,
                updated_at=datetime.fromisoformat(updated_at),
            )
            return Result.ok(updated_project)
        except sqlite3.Error as e:
            return Result.err(f"Database error: {e}")

    def delete(self, project_id: UUID) -> Result[bool]:
        """Delete a project."""
        try:
            cursor = self._conn.execute(
                "DELETE FROM projects WHERE project_id = ?",
                (uuid_to_str(project_id),),
            )
            # Note: Transaction commit is managed by the caller (UnitOfWork/transaction context)
            return Result.ok(cursor.rowcount > 0)
        except sqlite3.Error as e:
            return Result.err(f"Database error: {e}")

    def list(self, params: PaginationParams) -> Result[PaginatedResult[Project]]:
        """List projects with pagination."""
        try:
            # Get total count
            count_cursor = self._conn.execute("SELECT COUNT(*) FROM projects")
            total = count_cursor.fetchone()[0]

            # Get paginated results
            cursor = self._conn.execute(
                """
                SELECT * FROM projects
                ORDER BY created_at DESC
                LIMIT ? OFFSET ?
                """,
                (params.limit, params.offset),
            )
            rows = cursor.fetchall()
            projects = [project_row_to_dto(dict(row)) for row in rows]

            return Result.ok(PaginatedResult(
                items=projects,
                total=total,
                limit=params.limit,
                offset=params.offset,
            ))
        except sqlite3.Error as e:
            return Result.err(f"Database error: {e}")