"""Database schema package."""

from __future__ import annotations

from database.schema.ddl import (
    CREATE_INDEXES,
    CREATE_PROJECTS_TABLE,
    CREATE_SESSIONS_TABLE,
    CREATE_MEMORIES_TABLE,
    CREATE_MEMORY_LINEAGE_TABLE,
    CREATE_CUSTOM_INSTRUCTIONS_TABLE,
    CREATE_MEMORY_INDEX_METADATA_TABLE,
    CREATE_INSTRUCTION_INDEX_METADATA_TABLE,
    CREATE_SCHEMA_VERSION_TABLE,
    ALL_TABLES,
    SCHEMA_VERSION,
)

__all__ = [
    "CREATE_PROJECTS_TABLE",
    "CREATE_SESSIONS_TABLE",
    "CREATE_MEMORIES_TABLE",
    "CREATE_MEMORY_LINEAGE_TABLE",
    "CREATE_CUSTOM_INSTRUCTIONS_TABLE",
    "CREATE_MEMORY_INDEX_METADATA_TABLE",
    "CREATE_INSTRUCTION_INDEX_METADATA_TABLE",
    "CREATE_SCHEMA_VERSION_TABLE",
    "CREATE_INDEXES",
    "ALL_TABLES",
    "SCHEMA_VERSION",
]